### ISSUE TITLE
compatibility with flutter_local_notification status

### ISSUE THREAD

**Issue by vinnytwice** [MaikuB/flutterfire#2] opened 2020-03-18 08:37 UTC
@MaikuB Hi and thanks for the flutter_local_notification and the branch.
I read all the issues about the subject in flutter_local_notification and I have gotten lost track of the actual state of compatibility of your plugin with firebase_messaging as the issue is blocked.
As I'm gonna start implementing them I still have three questions:
Are the two plugins finally working well together both for background and foreground notifications?
Are custom actions handled  on both Android and iOS for both local and push notifications?
Are rich notifications supported on both platforms?
Dough 3rd question is not related to your plugin you might know the answer or have a reference to to it.
Thank you very much again.
Cheers

**Comment by MaikuB** [comment] 2020-03-18 08:45
This fork is here because it has the changes that from my testing and others testing, allows both to be used together. I would've assumed you found your way here from seeing that info. The issue is marked as blocked on the `flutter_local_notifications` repo because my PR for `firebase_messaging` hasn't been reviewed and merged by the team. There is info in the readme for `flutter_local_notifications` plugin on how to use the fork. 

Regarding actions, no for the `flutter_local_notifications`. I'm not sure about the state of support for actions for `firebase_messaging`.

**Comment by vinnytwice** [comment] 2020-03-18 09:00
@MaikuB I see, so still the only way to get both working is by using this fork.  I assume that at the time you created it, action weren't supported yet so using your fork wouldn't change that.
So if the master `firebase_messaging` would now support custom action, it would obviously still have conflicts with `flutter_local_notifications` plugin as your fork hasn't been merged yet, and then the only solution would be to fork master `firebase_messaging` myself and modify it as you did in this fork right? I think you explained what you did and the steps to reproduce it right? 

Thank you very much again.

**Comment by MaikuB** [comment] 2020-03-18 09:03
Yes that would be right though this fork currently has the latest changes for `firebase_messaging`

**Comment by vinnytwice** [comment] 2020-03-18 09:08
Ok.. so.. no actions yet.. I thought it might have changes as in you first message you said  

> I'm not sure about the state of support for actions for firebase_messaging.

So let's just hope they add support for it soon.  If/that will happen your fork will reflect them automatically? Very noob question I know, but I'm a noob so some basics as how GitHub forking works in detail still I have to fully grasp.

**Comment by MaikuB** [comment] 2020-03-18 09:12
> I'm not sure about the state of support for actions for firebase_messaging

This was more to do with me not having used FCM much. I haven't worked with sending push notifications for a while but off memory, actions appear based on what's in the push notification payload

> So let's just hope they add support for it soon. If/that will happen your fork will reflect them automatically?

No, I'll need merge them into my fork

**Comment by vinnytwice** [comment] 2020-03-18 09:28
> actions appear based on what's in the push notification payload
indeed they are..as I'm porting my app to flutter from  Swift and I wrote the push notification part a long time ago..I kinda forgotten about..
Sorry I got confused between questions..
to recap
Custom actions in `local_notification` are not supported, but will they?.( I need to trigger part of my app when an alarm goes off if user decided to trigger it)
And rich push notifications from `firebase_messaging`are still not supported right?

**Comment by MaikuB** [comment] 2020-03-18 09:32
> Custom actions in local_notification are not supported, but will they?

No. There's an existing issue on this that is marked as blocked as well.

> And rich push notifications from firebase_messagingare still not supported right?

As mentioned before, I don't use FCM much except to try to fix the compatibility issue so I'm not the best person to be asking this. I'd suggest to check the docs available or on a community forum/chat

**Comment by vinnytwice** [comment] 2020-03-18 10:05
got it . Thank you vey much

**Closed** 2020-03-18 10:06 UTC
Labels: bug

**Comment by vinnytwice** [comment] 2020-03-18 13:40
@MaikuB  I'm reading all issues and I might have found something.

In https://github.com/MaikuB/flutter_local_notifications/issues/111#issuecomment-596486855 pawlowskim reference to a message 
>UNUserNotificationCenter delegate received call to -userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler: but the completion handler was never called.

for  both setup 3 and 4. 
set 3 uses official `firebase_messaging`while setup 4 uses your fork of it.

I remembered that I got pretty frustrated when writing my Swift app (firebase docs are awful) until I implemented an `AppDelegate` method that is actually responsible for handling interactions with the notifications from `UNNotificationCenter`:

> //    The method will be called on the delegate when the user responded to the notification by opening the application, dismissing the notification or choosing a UNNotificationAction
>     @available(iOS 10.0, *)
>     func userNotificationCenter(_ center: UNUserNotificationCenter, didReceive response: UNNotificationResponse, withCompletionHandler completionHandler: @escaping () -> Void) {
>         print("didReceive response: user interacted with notification")


I had a look at the `AppDelegate` in your Swift sample app and is not implemented either.

Might be just a shot in the dark but it could/should be the reason why pawlowskim is getting that completion handler not called message when tapping on notifications. 
Have you implemented the method in your tests?
Let me know if you need more info and I'll share the complete method from my app.
Hope this helps.
Cheers.

**Comment by MaikuB** [comment] 2020-03-18 14:51
> I had a look at the AppDelegate in your Swift sample app and are not implemented either.

That's because it's not suppose to be there and is handled by the plugin.

**Comment by vinnytwice** [comment] 2020-03-18 17:22
Yes, I see it  now that I briefly tried your sample app linked to my firebase and saw that everything seems to be working as expected.
Well as a first try ( using your fork )  I get push notifications when app is either in background or foreground. When in foreground  `onSelectedNotification` method gets triggered  both when tapping on push and local notifications. When in background tapping on push notification   triggers `onResume:`.  I have been only able to receive test messages sent directly to token I have to admit, while messages sent to my app when selected in firebase console  don't show up, dough this should have to do with the way you app is set up right?

I still have to dig deep into firebase_messaging and flutter_local_notification as I need to use topics subscriptions for firebase_messaging, but as far as I've seen they both suite my needs. I could live without local notification actions and do what I need directly from `onSelectedNotification:` callback.
So the problem in all the issues opened is just with the master branch of `firebase_messaging` right?
Thank you very much.

**Comment by MaikuB** [comment] 2020-03-19 08:38
> When in foreground onSelectedNotification method gets triggered both when tapping on push and local notifications.

That shouldn't happen. Perhaps there's some confusion here as my example app displays a local notification to display the content if the push notification was received while the app was in the foreground.

>  I have been only able to receive test messages sent directly to token I have to admit, while messages sent to my app when selected in firebase console don't show up, dough this should have to do with the way you app is set up right?

Possibly an issue with how you've setup the provisioning profiles etc. I've used to console to send to the specified app and it worked fine. Note that I was running this using debug mode and the development provisioning profile I've setup for my sample app

> So the problem in all the issues opened is just with the master branch of firebase_messaging right?

I think I get what you're trying to say but to say it's master branch isn't accurate as this fork has a master branch. It's an issue in the original code/repo. Note that I've seen that my PR has been merged so it's likely an update will be released soon so that you no longer need to use this fork

**Comment by vinnytwice** [comment] 2020-03-19 11:46
@MaikuB 
I'm testing further using your sample app and I have two problems.

Problem 1: message type.

I have this behaviour that differs depending on the type of message is sent from FMC console wether proxy is set to Yes or NO in info.plist.

If I send message to token it all works as expected  and `onMessage:` gets called.
it then gets handled by 

```
await _flutterLocalNotificationsPlugin.show(
        0,
        message['aps']['alert']['title'],
        message['aps']['alert']['body'],
        platformChannelSpecifics,
      );
```

as the received message is :

`flutter: onMessage: {google.c.sender.id: 147151203258, google.c.a.e: 1, gcm.notification.sound2: default, aps: {alert: {title: h, body: h}, sound: default}, google.c.a.c_l: aps, gcm.n.e: 1, google.c.a.c_id: 628242881095762178, google.c.a.udt: 0, gcm.message_id: 1584616770359619, google.c.a.ts: 1584616770}`

When a general message is sent dough, `onMessage:` gets called but no handling
 handling is done by `_flutterNotificationPlugin.show` as the message is:

flutter: onMessage: {from: 147151203258, collapse_key: (omitted), notification: {tag: campaign_collapse_key_6709538423301995458, body: h, title: h, e: 1, sound2: default, sound: default}}.

I guess this is because the the message is different and doesn't get mapped by your plug in so doesn't get shown right?

Problem 2: background.

When app is in background token messages work as expected, while  with general message `onMessage:` doesn't get called until I open the app in foreground.

What should I look into?
Thank you very much.

**Comment by vinnytwice** [comment] 2020-03-19 11:54
@MaikuB 

> I think I get what you're trying to say but to say it's master branch isn't accurate as this fork has a master branch. It's an issue in the original code/repo. Note that I've seen that my PR has been merged so it's likely an update will be released soon so that you no longer need to use this fork

Yes I meant original repo, sorry. Great news I'm so glad your work gets merged!

as for the provisioning I'm using the same bundle id as for my original app so it's using a valid certificate, it shouldn't be the case.

**Comment by MaikuB** [comment] 2020-03-19 11:59
> I guess this is because the the message is different and doesn't get mapped by your plug in so doesn't get shown right?

This has nothing to do the plugin and the code is there for you to see that it's extracting what's there to display. You need to write the code to suit your own app's purpose

> When app is in background token messages work as expected, while with general message onMessage: doesn't get called until I open the app in foreground.

Please see the readme for the `firebase_messaging` plugin, which breaks down what callback is invoked in each circumstance.

Note that your questions don't relate to plugins I don't maintain and is no longer compatibility related, particularly now that my PR has been. So if you have questions relating to firebase, I'd kindly that you use the appropriate channels to do so, such as the original repository for `firebase_messaging` or one of the sites at https://flutter.dev/community

**Comment by vinnytwice** [comment] 2020-03-19 12:07
> This has nothing to do the plugin and the code is there for you to see that it's extracting what's there to display. You need to write the code to suit your own app's purpose

yes of course, I was only asking If I interpreted the behaviour correctly, based on the code you written ;)

> Note that your questions don't relate to plugins I don't maintain and is no longer compatibility related, particularly now that my PR has been.

yes of course, I was just asking if this behaviour is expected with your code.

No worries, I won't bother you any further.

**Comment by MaikuB** [comment] 2020-03-19 12:16
> yes of course, I was only asking If I interpreted the behaviour correctly, based on the code you written ;)

To clarify, the point I was trying to make was the mapping is done by the app, not the plugin. I've seen differences in the notification like what you showed even when I sent a notification to a token. This was resolved when I fixed some configuration issues, though can't remember the specifics except that I hadn't enabled the remote notifications capability (https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app)
